export const planetInSign1 = {
  suninaries: "Sun in beranu - rychlé myšlení a celková vznětlivost. Nejdřív mluví a pak se teprve zapojuje mozek. Lidé s Merkurem v Beranu jsou vášniví a velmi snadno se s vámi začnou hádat.",
  sunintaurus: "Sun in byk - rychlé myšlení a celková vznětlivost. Nejdřív mluví a pak se teprve zapojuje mozek. Lidé s Merkurem v Beranu jsou vášniví a velmi snadno se s vámi začnou hádat.",
  merkurvberanu: "Merkur v Beranu - rychlé myšlení a celková vznětlivost. Nejdřív mluví a pak se teprve zapojuje mozek. Lidé s Merkurem v Beranu jsou vášniví a velmi snadno se s vámi začnou hádat.",
  merkurvbyku: "Merkur v Býku - mohou být umínění a houževnatí, psychicky jsou ale velmi stabilní. Jejich myšlení může být pomalejší. Trvá jim dlouho, než se rozhodnou. Tíhnou ke konvenčním přístupům a jsou praktičtí.",
  merkurvblizencich: "Merkur v Blížencích - vtipní a zábavní lidé. Dokážou bez přestání mluvit a ptát se vás na spoustu věcí. Píší dlouhé e-maily a neustále brebentí. U negativně aspektovaného Merkura je zde sklon k povrchnosti.",
  merkurvraku: "Merkur v Raku - vlídná a jemná řeč a komunikace. Jsou sentimentální, bystří, emocionální a přátelští. Někdy mají zbytečné obavy a dělají z komára velblouda. Dokážou dobře uspat dítě. Jejich komunikace je uklidňující.",
  merkurvelvu: "Merkur ve Lvu - Merkur je planetou komunikace a Lev je znamením herců a showbyznysu. Člověk s Merkurem ve Lvu dokáže získat naši pozornost a komunikuje tak, aby byl středem pozornosti.",
  merkurvpanne: "Merkur v Panně - tento Merkur je prostě úžasný. Merkur - mysl Panna = záliba v detailu přerůstající až do hnidopišství. Někdy mohou druhým připadat poněkud vážní a upjatí.",
  merkurvevahach: "Merkur ve Vahách - chce produkovat krásné myšlenky, říkat, slyšet, číst a psát krásná slova. Zábavné osoby na večírcích a společenských akcích. Uhlazená komunikace. Tito lidé jsou skvělí, protože dokážou vnést do rozhádané společnosti klid a harmonii. Dobří vyjednávači. Jsou okouzlující.",
  merkurvestiru: "Merkur ve Štíru - tito lidé jdou opravdu do hloubky. Chtějí věcem přijít na kloub a vyzkoušet, jestli fungují. Myšlení prošpikované sexualitou. Silní a tiší. Milují tajemství. Mohou mít potřebu mluvit sprostě, protože mají hříšné myšlenky - v tom dobrém slova smyslu.",
  merkurvestrelci: "Merkur ve Střelci - spokojení a optimističtí lidé, kteří dokážou zničehonic vytáhnout z rukávu vtip, který ostatní rozesměje. Někdy mohou ostatní peskovat. Vyžadují pozornost. Jsou lehkomyslní. Často potřebují pracovat na tom, aby dokázali převzít zodpovědnost.",
  merkurvkozorohu: "Merkur v Kozorohu - seriózní myšlení a autoritativní hlas, který druzí lidé dokážou brát bez problémů vážně. Mají rádi historii. Tíhnou k logickému myšlení a hledání pravdy. Mají potřebu pevného charakteru.",
  merkurvevodnari: "Merkur ve Vodnáři - svobodní myslitelé. Vodnář je zároveň planetou moderních technologií a výpočetní techniky. Tito lidé mohou mít v myšlení náskok před většinou populace. Někdy jsou brutálně upřímní a potřebují pracovat na tom, aby byli v komunikaci citlivější.",
  merkurvrybach: "Merkur v Rybách - vizionáři, kteří dokážou vidět velmi široký horizont. Snílci se sklonem k poezii. Někdy jsou příliš romantističtí a idealističtí. Fanoušci hudby a filmu. Zajímá je umění.",
  marsvberanu: "Mars v Beranu - tito lidé jdou tvrdě za tím, co chtějí. Překypují touhou. V tu chvíli je lepší se jim klidit z cesty!",
  marsvbyku: "Mars v Býku - dosahují úspěchu silou vůle. Jsou praktičtí a silně sexuálně založení.",
  marsvblizencich: "Mars v Blížencích - bojují s pomocí slov. Jsou entuziastičtí a potřebují svobodu. S pomocí slov dokážou vzrušit svůj protějšek.",
  marsvraku: "Mars v Raku - silná potřeba chránit. Snaží se budovat pevnosti. V tomto znamení je postavení Marsu velmi problematické.",
  marsvelvu: "Mars ve Lvu - tyto osoby mají silnou energii a vitalitu, jednají rychle. Jsou jako stvoření postavit se do čela nějaké skupiny či smečky.",
  marsvpanne: "Mars v Panně - všechno se točí kolem disciplíny a povinností. Mohou být obdařeni tělesnými přednostmi. Dokážou postupovat strategicky.",
  marsvevahach: "Mars ve Vahách - možné spory a hádky v partnerském vztahu. Tuto energii je ale lepší nasměrovat do klidu.",
  marsvestiru: "Mars ve Štíru - trochu temný charakter. Opravdu silné zaměření na sex a vášeň. Energie Marsu ve Štíru pudí člověka do dramatických situací plných vášně.",
  marsvestrelci: "Mars ve Střelci - neohraničená energie a dobrodružný duch. Osobnost, která nemá ráda mantinely a omezení.",
  marsvkozorohu: "Mars v Kozorohu - tito lidé jsou ctižádostiví. Protože jsou velmi ambiciózní, měli by si dávat pozor na své bezohledné chování, k němuž mají občas sklon.",
  marsvevodnari: "Mars ve Vodnáři - postavení v tomto znamení způsobuje mírnou nervovou rozkolísanost. Občas potřebují vysadit. Jejich povaha je dynamická. Bojují za lidská práva.",
  marsvrybach: "Mars v Rybách - bohatství citů a pocitů. Tyto osoby někdy nevědí, jak tuto energii ventilovat ven. Velmi dobrým pomocníkem je v tom například jóga nebo taiči.",
  venusevberanu: "Venuše v Beranu - Beran disponuje velmi výbušnou energií, a když touto energií naplní planetu lásky a peněz, bude opravdu vášnivý milostný partner. Venuše v tomto znamení získává sílu, ale i značnou atraktivitu.",
  venusevbyku: "Venuše v Býku - zdravíme feromony! Krásní, elegantní a přitom velmi zemití lidé. Milují smyslné doteky. Jsou dobří v kuchyni a mohou se stát dokonce profesionálními kuchaři. Muži s Venuší v Býku vědí, po čem ženy opravdu touží.",
  venusevblizencich: "Venuše v Blížencích - milují slova a také lidi, kteří pracují se slovy. V lásce mohou být rozkolísaní a přelétaví. Omezený rozhled, co se týče peněz. Jejich vydělávání u nich může souviset s tím, že nějak vyjadřují svou osobnost. Rádi flirtují.",
  venusevraku: "Venuše v Raku - tito lidé jsou přátelští a starostliví. V jejich přítomnosti se budete cítit jako doma, možná také díky jídlu, které pro vás připraví. Umějí se se svým partnerem mazlit. Umějí také vytvořit pocit domácí pohody. Chrání své potomky.",
  venusevelvu: "Venuše ve Lvu - touží po tom, aby okouzlovali, což se jim daří i v pokročilém věku. Když jsou ve společnosti, chtějí, aby je doprovázela nějaká atraktivní a krásná osoba. Obklopují se také krásnými věcmi. Ženy s Venuší ve Lvu jsou opravdové princezny.",
  venusevpanne: "Venuše v Panně - miluje detaily. Tato osoba si vás bude hledět a bude se o vás starat. Může na vás mít zároveň trochu vyšší nároky a občas vás kritizovat (pokud jí na vás záleží). Má ráda, když je její partner či partnerka čistý a voní, nejlépe mýdlem. Za zavřenými dveřmi se dokáže sexuálně odvázat.",
  venusevevahach: "Venuše ve Vahách - toto je bezesporu nejlepší postavení Venuše. Sladká, jemná a s bezvadným chováním. Muži s Venuší ve Vahách vám klidně políbí ruku. Hlavní varování - milují lásku, ale musí to být příjemná a pohodová láska. Dokonalí romantici. Je pro ně přirozené mít vztah.",
  venusevestiru: "Venuše ve Štíru - tady máme temnou a svůdnou Venuši. Určitě vám neodhalí všechna svá tajemství. Muži i ženy s Venuší v tomto znamení mohou mít sklon skrývat v sobě doutnající vášně, například žárlivost. Jsou to velmi intenzivní emoce.",
  venusevestrelci: "Venuše ve Střelci - přelétaví milenci, kteří mohou být dnes tady a zítra už někde úplně jinde. Nebojí se dát vám najevo, že je zajímáte. Jsou svobodní, nespoutaní a nechtějí se pevně vázat (a nemají rádi, když se někdo váže na ně).",
  venusevkozorohu: "Venuše v Kozorohu - toto je trochu tvrdé sousto, protože tito lidé se často bojí nebo mají pocit, že nejsou dostatečně milovaní. Jsou to velice důvěryhodní milenci, kteří vás nenechají na holičkách, pokud je ovšem zrovna něco nevyděsí.",
  venusevevodnari: "Venuše ve Vodnáři - osoba s Venuší v tomto znamení bude hledat nějakého nekonvenčního milence či milenku. Jeden z typů, který se nerad váže a kroužkuje. Úskalí spočívá v tom, že tito lidé žijí spíše v hlavě než v srdci. Dokážou být elegantní a jejich šatník může obsahovat kvalitní módu. Mají spoustu přátel. Jsou to idealisté.",
  venusevrybach: "Venuše v Rybách - jsou to vlídní fantasté, někdy jsou příliš měkcí a sentimentální, a nehodí se proto do dnešní moderní doby. Milují lásku a fantazii. Mají bohatý citový život a přitahují lidi svou vřelostí. Někdy se dívají na svět růžovými brýlemi.",
  jupitervberanu: "Jupiter v Beranu - lidé plní toho, čemu Francouzi říkají joie de vivre - radosti ze života. Vzrušení a neutuchající chuť užívat si zábavu a různé společenské akce. Svéhlavost a rebelství.",
  jupitervbyku: "Jupiter v Býku - tito lidé mohou mít úspěch ve finančních záležitostech. Milují rozkoš, jsou shovívaví, ale také žárliví. Mají spojení s božskou ženou v sobě.",
  jupitervblizencich: "Jupiter v Blížencích - jsou to velmi výřeční, otevření a chytří lidé. Hodně flirtují a cestují. Přitahují změny nebo je sami iniciují.",
  jupitervraku: "Jupiter v Raku - vlídní a soucitní lidé. Jídlo a jeho příprava je pro ně dobrodružstvím. Tíhnou k rodinným záležitostem. Jsou také velmi empatičtí a citoví.",
  jupitervelvu: "Jupiter ve Lvu - okázalost a předvádění se. Velkomyslnost. Dokážou oslnit. Přitakání životu.",
  jupitervpanne: "Jupiter v Panně - věnují velkou pozornost detailům. Jsou kritičtí, velmi praktičtí a někdy až přízemní. Drží se hmatatelných hodnot a faktů.",
  jupitervevahach: "Jupiter ve Vahách - elegantní a společenští lidé se sklonem k umění. Milují lásku a je pravděpodobné, že budou v životě hodně milovat. Často populární a atraktivní jedinci.",
  jupitervestiru: "Jupiter ve Štíru - neuchopitelné až tajemné osoby. Jsou sexy. Velká část jejich osobnosti je skrytá a mohou mít mnoho tajemství. Působí důstojně.",
  jupitervestrelci: "Jupiter ve Střelci - dobrodruzi, cestovatelé a lidé, kteří mají rádi riziko. Temperamentní a bezstarostní.",
  jupitervkozorohu: "Jupiter v Kozorohu - pragmatičtí, svědomití a dobře fungující jedinci. Dokážou být disciplinovaní a mít sami sebe pod kontrolou. Dělají si velké plány a užívají si práci.",
  jupitervodnari: "Jupiter ve Vodnáři - vlastní velké množství různých přístrojů, užívají si vývoj v oblasti techniky a počítačů. Jsou lidští a rádi se zapojí do různých prospěšných projektů.",
  jupitervrybach: "Jupiter v Rybách - intuice až parapsychologické schopnosti. Užívají si sny a blouznění. Jsou to dobráci, někdy až bezstarostní a vyžívají se ve svých vlastních pocitech.",
  uranvberanu: "Uran v Beranu - tito lidé se chovají jako rebelové, nedají se ničím svázat a ignorují všechny, co se o to chtějí pokusit. Jsou trochu divocí.",
  uranvbyku: "Uran v Býku - překvapivě romantičtí a romanticky překvapiví jedinci. Musí si dát jenom pozor na sebestřednost a zatvrzelost.",
  uranvblizencich: "Uran v Blížencích - schopnost svobodně myslet, moderní myšlenky a originální nápady. Vynálezci.",
  uranvraku: "Uran v Raku - jejich rodina a domov mohou být trochu chaotické nebo mohou být součástí nějaké velmi moderní rodiny, která žije nekonvenčním životním stylem. Excentrici.",
  uranvelvu: "Uran ve Lvu - rebelové se sklonem k hysterii. Tito lidé dokážou jít proti proudu a nenechat se strhnout většinou, jsou kreativní a milují, když se věci hýbou progresivně kupředu. Jedinečná schopnost sebevyjádření.",
  uranvpanne: "Uran v Panně - možnost progresivního vývoje v oblasti alternativní medicíny a léčení na základě energie. Změny a revoluce v postavení žen. Chytrost.",
  uranvevahach: "Uran ve Vahách - změna v partnerských vztazích a jejich pravidlech. Nezávislí romantici. Možnost fungování partnerství na základě různých modelů.",
  uranvestiru: "Uran ve Štíru - progresivní vývoj v oblasti sexuality. Obracení zaběhlých myšlenek vzhůru nohama. Tito lidé by si měli dávat pozor na pomstychtivost a na své vyhrocené emoce.",
  uranvestrelci: "Uran ve Střelci - někdy trochu nevybíravé chování a snaha o progresivní postup za každou cenu. Unáhlení, neortodoxní, nervózní.",
  uranvkozorohu: "Uran v Kozorohu - bourání konvencí v oblasti kariéry, neúnavní a špičkoví pracovníci s inovativním přístupem.",
  uranvvodnari: "Uran ve Vodnáři - zájem o vědu. Lidumilní humanisté, kteří se snaží posunout svět do budoucnosti. Talent na digitální technologie. Vynálezy. Touha po svobodě.",
  uranvrybach: "Uran v Rybách - idealismus. Nové myšlenky v oblasti mystiky. Modernizace hudby a umění. Nestálost a náladovost.",
  neptunvberanu: "Neptun v Beranu - silné puzení prozkoumávat tajemství nevědomí. Podvratné a sabotážní tendence. Idealismus.",
  neptunvbyku: "Neptun v Býku - milující lidé se sklonem k hudbě a umění. Okouzlující vizionáři. Dokážou vydělat peníze v oblasti umění a spirituality.",
  neptunvblizencich: "Neptun v Blížencích - tyto osoby dokážou snít za bílého dne. Žijí ve svých fantaziích a mohou je také zachycovat v písemné formě. Mají velkou představivost. Někdy jsou ustaraní.",
  neptunvraku: "Neptun v Raku - snílci, jejichž fantasknost se promítá do podoby jejich domova a rodiny. Jsou milí, citoví, líní a mají velkou empatii.",
  neptunvelvu: "Neptun ve Lvu - lidé showbyznysu a jiných oblastí, kde se překrucuje realita. Budou pravděpodobně plní nerealistických představ o tom, jak jsou úžasní. Dokážou být kreativní.",
  neptunvpanne: "Neptun v Panně - zmatení a zároveň kritičtí jedinci. Nejsou si jistí tím, co vlastně chtějí. Idealistické představy o zdraví a službě ostatním.",
  neptunvevahach: "Neptun ve Vahách - sní o krásných věcech, umění a módu. Mohou být zmatení v oblasti práva a zákonů. Romantičtí vizionáři. Milostný vztah s nimi je jako sen.",
  neptunvestiru: "Neptun ve Štíru - sexuální fantazie. Pletichy a intriky v sexuální oblasti. Tito lidé jsou tajnůstkáři, často sarkastičtí a přitahuje je okultismus.",
  neptunvestrelci: "Neptun ve Střelci - sní o cestování. Jsou idealističtí a touží splynout se životem prostřednictvím cestování a studia. Utopisté.",
  neptunvkozorohu: "Neptun v Kozorohu - kalkulující myšlení. Svými nápady dokážou inspirovat lidi v byznysu. Nové způsoby práce. Idealisté v pracovní oblasti.",
  neptunvvodnari: "Neptun ve Vodnáři - touha pomáhat lidem. Dobročinnost. Komunikace s druhými po síti. Sní o svobodě.",
  neptunvrybach: "Neptun v Rybách - duchovní probuzení. Jemní lidé, kteří se nesvazují pevnými mantinely života. Silní romantici žijící ve svých snech.",
};